### ISSUE TITLE
Twenty months home from the war article would be even better if it references airborne/aerosols

### ISSUE THREAD

**Issue by paul-hammant** [famulare/famulare.github.io#6]
Airborne/aerosols being the principle mechanism of transmission, as you know sir. Not droplets/fomites we were told at the start.  I think it is worth calling out. I note that you use code words - "partisan symbol on my face" - so you could carry on in that style, but your article would be even better if it called out the folly of controlling for droplets under gravity and the surfaces they coat being a danger to digits, mouths and droplets.

**Comment by famulare** [comment]
Fair point Paul.  I don’t actually refer to what the engineering problem is—cleaning the air—and as this post goes a bit wider, that would be nice to add.

**Comment by famulare** [comment]
I also don’t know why your comment isn’t showing up on the post. Must be a bug with my utterances integration.

**Comment by famulare** [comment]
Oh! Because it wasn’t sent as an utteranc.es post in the form at the bottom!
